###
# Login
POST https://api2.ghin.com/api/v1/golfer_login.json HTTP/1.1
content-type: application/json

{
    "user": {
        "password": "G0lf$ucks69!",
        "email_or_ghin": "50155",
        "remember_me": false
    },
    "token": "jsGlqh9tkXvkLzDIM7iTnUH3tcB1oG18C8lOSqVumvRaWDCXxWjBFzdKrpsAzyT4o0GJkagmaop5AdoKj2+jP1km5Nd2B712/psGAoOMITJojq1l6aI3J6N18uh1icWj1vFEttute048dW8RveJIkdJJ5Or2dKr7yRmI3LkQ68DZ4gvuLL6s/JqnqAD2jgfQCqWYFJfUVEnrfvZylIfpWs4mSmQ1Tq+3TJ2MWyIU4pOWmeRZ/9pO2KtDTj3IIGov8d+6f9MKVuZELcGUGPBJi70rHr8S8OTIurl+yEqF0Ie7gGbF5FSfPBo70T5A5/L1dvlTzHEAH2DR+CueYhCQ+MmUX1OvHSozKiWqetZ0nr1V53iLC/dOcjveYTktih3PtDcTn6cZtoIdeiNxsC5VW4XaXNyS9YMRgjZ/EIXSku79JUvQL00WL2QEHdt34uiEk/VSr3m0VFwe8LGoWgSiEEQZpK+/ml+67b3JXynoE9uO1mlhOGKpysUd66OKs64rN+HRJyIVgySampR/svUPidm9bQJ1rHKGsoppJY3om93/AxH1mdP8GN+N4krac3PoSOc3npvUuBAleMsiD/FahrFFUrh4fEnCVnsHSc3Gx6xv0Nj0fjzMaC4x5tvWhBz9m1arVGO3Jb8G8qFOKGvUA3KF3dWIl/CoQh2tf0pKtWs=",
    "user_token": "03AFcWeA7IiEDdfcowFMDoRNq5EJn-kxWBF0jM9aOkrJzl21gZvI4xAKkUxwoV-e9u0XzfoRi2oNtags1BBJ1VeCSu3lZRHWI4ddg5F-8W88tIZ7QTX8xSdOw5EXLhM-Hdmc6awqxoGhnpDkJoV5MnfTDPOtb2AT-6dHw53U0wW-0w9zWJODjTPemRda224aBfacCTdhe06AKkioOfoyT9TcX_82HaFWeHLgiWJJaANJLO7Tzr7WwatcDr7RPBXqN8vddvr3Yd7LEaqhPDNiL3_LQZ4kbijSVbPoYuPGENe0BY0XTdppABmiYRxTQNSyBVbWPIv8D6b1vka_hrulhp8FuuuNuMTbwIVLWhVDuSq5Lfk53Ehcij7ksHHEkF7_UY0rvsLUouYybGPBe_RZcJ1r2XWYgJV7C-w8RCyQP1Xb2u89X_Lp22b2uANlBRKSp8LMOG2N4k4pp2JGCnsgO9m2Th_CtKjpKjeQmiRc70q0fSGCJE8vLvZVdWYhULXKNueo1BVj0FFBpzcGrRHdfODf4qBNibR5PRUkpmtBsVGdb1NYp4FLQUljUNmm3qhp0iBx4pA37azH5HC2W_EfeBmqeaNUrZhn6zaDVxFUhpaNmEummKr1cvW3sBSJcAR3gPolWLyFSkUaHDnVjEQaoHpN-RfYl1wkXY_-RCAiFMBJyjpqXJVpw1O-213PuGWJpevzzjBg1JbgDaGDGqZNySZrxqcBqCgrGQOPLJPzgGAqMUG1QvNvzs_G8bYYfPAbReYAPDtq3b_QQ0punRKpSwl0QYUwdRz6mskPw7-SxapFdPGNFYNsCktxBV9z3fmKMyS9dCZxe90IQjbUPS2rP0f03SnpA70ebBrVfqr1d25RJxfIUftoUMd8jUz5irO8PypFAyDiHd_jKoZNANx8MXRTeBiaZu3jxYZCRSV0hpXmdRXGlUUChmRpM",
    "source": "GHINcom"
}